version: "3.9"
services:
  ticdrive-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
