name: Deploy to Azure

on:
  push:
    branches:
      - main # Triggers the workflow when changes are pushed to the "main" branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure using the Service Principal
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Deploy to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: <YOUR_APP_SERVICE_NAME> # Replace with your Azure App Service name
          slot-name: production # Optional: use "production" unless deploying to a staging slot
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
